### ISSUE TITLE
Support Templates

### ISSUE THREAD

**Issue by HerrNiklasRaab** [Testura/Testura.Code.UnitTestGenerator#3]
We are in a company, were we have to add an Attribute before every Method an before every class. For example:

> [Developer(DeveloperName="Niklas")]

Can you implement something like this?

**Comment by MilleBo** [comment]
Sure that shouldn't be a problem to generate. The question are how flexible you need it to be? 

For example is it enough to day "all classes should also have x attribute" and "all methods should also have y attribute"? Or do you need to configure it so only specific classes or methods have them? 

If it's the first case I guess we could even do this (just an example):

```c#
var unitTestGenerator = new UnitTestGenerator();

unitTestGenerator.ClassAttributes.Add(new Attribute("DeveloperClass", new List<IArgument>() { new ValueArgument("Niklas")))
unitTestGenerator.MethodAttributes.Add(new Attribute("DeveloperMethod", new List<IArgument>() { new ValueArgument("Niklas")))
unitTestGenerator.GenerateUnitTests(DllPath, TestFrameworks.NUnit, MockFrameworks.Moq, OutputDirectory);
 ```
It's the most simple solution, not that flexible though and you can't change the argument for different classes/method.

**Comment by HerrNiklasRaab** [comment]
No thats perfekt, 👍 do you provide a visual studio plugin? Something like right click on class, "generate unit test"?

**Comment by MilleBo** [comment]
Sadly no. This project was build as an example of for my code generation library (https://github.com/Testura/Testura.Code) so it don't contain a lot of functionality. 

But I can try to add the functionality to add attributes this weekend.

**Comment by HerrNiklasRaab** [comment]
No Rush, for me and our company this project is only helpfull, if you can use it as Visual Studio Plugin. I understand it wrong, from the beginning :(

**Comment by MilleBo** [comment]
Oh I see, well then it's better to look at other alternatives I think. I think it's other that made similar things so maybe you can find something that fit your company better.
